fix: updated positioning logic in tooltips (#UX-184)
positive-js/mosaic pull request #514
Opened 2020-10-23 15:23 UTC by dron1ch

There is an issue with this pr. When the height of tooltip is bigger than the height of the host element it looks quiet bad. This happens because the positioning of the arrow is [hardcoded at the moment](https://github.com/positive-js/mosaic/blob/a5e64ffb54aea3e8136fedc18ecb2d4bc63d939f/packages/mosaic/tooltip/tooltip.scss#L71).

![pr](https://user-images.githubusercontent.com/13451179/97022029-4d1f3f00-155c-11eb-8206-a20a755cf73c.jpg)

2020-10-24 09:01 UTC, dron1ch commented
Не шмог спокойно спать, пофиксил позиционирование стрелки.

2020-10-27 13:08 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +    Default = 'default'
Нужно исходить из логики, что если положение не задано, то берется какое то из списка возможных. В данном случае default это возможное положение, которое в итоге будет = другому положению...

так же в cdk ангуляра есть HorizontalConnectionPos и VerticalConnectionPos.

2020-10-27 13:08 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +                `${
почему не в одну строку ?

2020-10-27 13:08 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +                const arrowElemRef = this.getTooltipArrowElem();
можно не на прямую лезть в дом, а добавить биндинги на .mc-tooltip-arrow

2020-10-27 14:14 UTC, dron1ch commented on packages/mosaic/tooltip/tooltip.component.ts
> +    Default = 'default'
@lskramarov 
Тут прикол в том, что в текущий момент положение стрелочки по умолчанию регулируется стилями, которые были повешены на элемент. Это может быть и 0 и 100500. Поэтому я остановился на default.

2020-10-27 14:16 UTC, dron1ch commented on packages/mosaic/tooltip/tooltip.component.ts
> +                `${
почему в одну?

2020-10-27 14:29 UTC, Fost commented on packages/mosaic/tooltip/tooltip.component.ts
> +    Default = 'default'
@lskramarov может взглянуть на POSITION_MAP? аналогично popover

2020-10-27 16:52 UTC, mikeozornin commented
Сломался right-top (бывший right) и left-top (бывший left):
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1744928/97334530-e8325480-188d-11eb-803a-f27b2f3a7519.png">

2020-10-27 16:52 UTC, mikeozornin requested changes
↑

2020-10-28 06:44 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +    Default = 'default'
> @lskramarov может взглянуть на POSITION_MAP? аналогично popover

он как раз и использует HorizontalConnectionPos и VerticalConnectionPos и получается всего 5 положений + комбинации. Вообще конечно зависит от того что тут пытались реализовать и возможно ты прав и нужно взять все ключи из POSITION_MAP, но тогда мне непонятно почему здесь только 'center'.

> Тут прикол в том, что в текущий момент положение стрелочки по умолчанию регулируется стилями, которые были повешены на элемент. Потенциально это может быть и 0 и 100500. Поэтому я остановился на default.

строковое значение 'default' нужно в любом случае убрать, оно избыточно, потому что дефолтное значение это когда ничего не задано и для этого не нужно писать [mcArrowPlacement]="'deafult'" а просто не указывать параметр.

2020-10-28 06:56 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +                `${
Да все норм, ревью как раз для этого, все загнать в форматеры и линтеры в любом случае не получится.

Теперь попытаюсь объяснить почему это выглядит дико... открывая документацию я вижу следующее:
![image](https://user-images.githubusercontent.com/9027254/97402090-04bca400-1903-11eb-87af-7f558cb11237.png)

и собственно я нигде не встречал, что бы выражение было с пробелами и переносами.

2020-10-28 07:40 UTC, Fost commented on packages/mosaic/tooltip/tooltip.component.ts
> +    Default = 'default'
мы еще ожидаем обновление UX гайдов.
на текущий момент следующие позиции – ```topRight(left)``` & ```center (left & right)```


важно, чтобы параметры позиционирования у всех компонент были одинаковыми.

2020-10-28 09:06 UTC, lskramarov commented on packages/mosaic/tooltip/tooltip.component.ts
> +                const arrowElemRef = this.getTooltipArrowElem();
обсудили сходу не взлетело позже нужно будет посмотреть.

2020-10-28 09:06 UTC, lskramarov approved these changes

2020-10-28 09:16 UTC, Fost commented
> Сломался right-top (бывший right) и left-top (бывший left):
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/1744928/97334530-e8325480-188d-11eb-803a-f27b2f3a7519.png">

@dron1ch все еще неверно позиционируется.

Должно быть вот так (как и было ранее):

![image](https://user-images.githubusercontent.com/567760/97416300-4eaf8500-1917-11eb-996f-11ddf49d7b0b.png)

2020-10-28 15:34 UTC, dron1ch reviewed
> > Сломался right-top (бывший right) и left-top (бывший left):
> > <img alt="image" width="474" src="https://user-images.githubusercontent.com/1744928/97334530-e8325480-188d-11eb-803a-f27b2f3a7519.png">
> 
> @dron1ch все еще неверно позиционируется.
> 
> Должно быть вот так (как и было ранее):
> 
> ![image](https://user-images.githubusercontent.com/567760/97416300-4eaf8500-1917-11eb-996f-11ddf49d7b0b.png)

Пофиксил, сорри.

2020-10-28 18:38 UTC, mikeozornin commented
Сверху чуть меньше, чем снизу:
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1744928/97481401-d58b4e80-1965-11eb-8e2c-09cecf74d3df.png">

Это можно как-то легко поправить? Если нельзя, то пропустите.

2020-10-30 10:14 UTC, dron1ch commented
Пофиксил, запушил.

2020-10-30 10:20 UTC, mikeozornin approved these changes

2020-10-30 12:13 UTC, merged