feat(input): input password (#UIM-716) WIP
positive-js/mosaic pull request #821
Opened 2022-02-21 17:30 UTC by lskramarov

2022-03-06 07:09 UTC, Fost approved these changes

2022-03-15 09:10 UTC, PositiveJS commented
Preview docs changes for 3acbbbd at https://positive-js.github.io/mosaic-previews/pr821-3acbbbd/

2022-03-15 09:31 UTC, PositiveJS commented
Preview docs changes for bdeeef3 at https://positive-js.github.io/mosaic-previews/pr821-bdeeef3/

2022-03-15 09:43 UTC, PositiveJS commented
Preview docs changes for 7b3c1cc at https://positive-js.github.io/mosaic-previews/pr821-7b3c1cc/

2022-03-15 09:53 UTC, PositiveJS commented
Preview docs changes for b664935 at https://positive-js.github.io/mosaic-previews/pr821-b664935/

2022-03-16 13:36 UTC, rmnturov commented
- Неправильный стиль кнопки Показать/скрыть пароль (цвета)
- Добавить тултип не кнопку Показать/скрыть пароль
- в примере. ввел 4 цифры, а система мне уже говорит, что соблюдено требования от 8 до 16 символов
- Было бы супер не убирать рамку фокуса у инпута в момент нажатия мышкой на переключатель Показать/скрыть пароль
- Давай сделаем возможность задать разную ширину для пароля и списка требований (например, имеем широкий контейнер, в который ставим короткое поле пароля (фикс. ширина под 8 символов), а подсказки тянутся на всю ширину контейнера)

2022-03-16 13:38 UTC, rmnturov requested changes
- [ ] Неправильный стиль кнопки Показать/скрыть пароль (цвета) в светлой теме
- [ ] Добавить тултип не кнопку Показать/скрыть пароль
- [ ] в примере. ввел 4 цифры, а система мне уже говорит, что соблюдено требования от 8 до 16 символов
- [ ] Было бы супер не убирать рамку фокуса у инпута в момент нажатия мышкой на переключатель Показать/скрыть пароль
- [ ] Давай сделаем возможность задать разную ширину для пароля и списка требований (например, имеем широкий контейнер, в который ставим короткое поле пароля (фикс. ширина под 8 символов), а подсказки тянутся на всю ширину контейнера)

2022-03-21 13:22 UTC, lskramarov commented
> * [x]  Неправильный стиль кнопки Показать/скрыть пароль (цвета) в светлой теме
> * [x]  Добавить тултип не кнопку Показать/скрыть пароль
> * [x]  в примере. ввел 4 цифры, а система мне уже говорит, что соблюдено требования от 8 до 16 символов
> * [x]  Было бы супер не убирать рамку фокуса у инпута в момент нажатия мышкой на переключатель Показать/скрыть пароль
> * [ ]  Давай сделаем возможность задать разную ширину для пароля и списка требований (например, имеем широкий контейнер, в который ставим короткое поле пароля (фикс. ширина под 8 символов), а подсказки тянутся на всю ширину контейнера)

@rmnturov поправил все кроме последнего пункта, можно смотреть.

Насчет последнего пункта:

Мы везде придерживались правила, что hint не может быть шире самого поля, у нас так в формах и везде на макетах:

![image](https://user-images.githubusercontent.com/9027254/159269124-c62a657b-2f2c-43c1-b172-81926624567c.png)

по каким причинам здесь вдруг решили изменить подход ?

Если такой функционал действительно нужен, то нужно его описать в гайде и добавить макет с примерами (возможно макет конкретного кейса)

2022-03-22 08:45 UTC, PositiveJS commented
Preview docs changes for 037780d at https://positive-js.github.io/mosaic-previews/pr821-037780d/

2022-03-22 10:27 UTC, rmnturov commented
> > * [x]   Неправильный стиль кнопки Показать/скрыть пароль (цвета) в светлой теме
> > * [x]   Добавить тултип не кнопку Показать/скрыть пароль
> > * [x]   в примере. ввел 4 цифры, а система мне уже говорит, что соблюдено требования от 8 до 16 символов
> > * [x]   Было бы супер не убирать рамку фокуса у инпута в момент нажатия мышкой на переключатель Показать/скрыть пароль
> > * [ ]   Давай сделаем возможность задать разную ширину для пароля и списка требований (например, имеем широкий контейнер, в который ставим короткое поле пароля (фикс. ширина под 8 символов), а подсказки тянутся на всю ширину контейнера)
> 
> @rmnturov поправил все кроме последнего пункта, можно смотреть.
> 
> Насчет последнего пункта:
> 
> Мы везде придерживались правила, что hint не может быть шире самого поля, у нас так в формах и везде на макетах:
> 
> ![image](https://user-images.githubusercontent.com/9027254/159269124-c62a657b-2f2c-43c1-b172-81926624567c.png)
> 
> по каким причинам здесь вдруг решили изменить подход ?
> 
> Если такой функционал действительно нужен, то нужно его описать в гайде и добавить макет с примерами (возможно макет конкретного кейса)

Спасибо за доработки. Договоренности про ширину, как оказалось, не существует. Возможность сделать поле, примечание, лейбл разной ширины нужна. Сделаем это в отдельной задаче.

2022-03-22 10:28 UTC, rmnturov reviewed
всё круто

2022-03-22 10:30 UTC, rmnturov commented
закрыл по ошибке. открываю

2022-03-22 10:56 UTC, PositiveJS commented
Preview docs changes for 6a0c254 at https://positive-js.github.io/mosaic-previews/pr821-6a0c254/

2022-03-22 10:58 UTC, PositiveJS commented
Preview docs changes for 2689a70 at https://positive-js.github.io/mosaic-previews/pr821-2689a70/

2022-03-22 11:01 UTC, merged